#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER dev WITH SUPERUSER PASSWORD 'dev';
	CREATE DATABASE courses;
	ALTER DATABASE courses OWNER TO dev;
	GRANT ALL PRIVILEGES ON DATABASE courses TO dev;
EOSQL